services:
    db:
      image: postgres:18.3-alpine3.23
      environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "myfinance_db"
      ports:
        - "5432:5432"
      volumes:
        - myfinance_db:/var/lib/postgresql

volumes:
  myfinance_db: